export type FieldPlanSnapshot = {
  referenceEpochMs: number;
  timeOffsetMs: number;
  latencySkewMs: number;
  selectedFlightId: string | null;
  flightCallSign: string | null;
  flightId: string | null;
  obsLat: number;
  obsLng: number;
  obsH: number;
  moonAz: number;
  moonAlt: number;
  moonR: number;
  photoSummary: {
    toImpactSec: number | null;
    transitMs: number | null;
    omegaDps: number | null;
  };
};

function fmtTime(ms: number): string {
  return new Date(ms).toISOString();
}

function fmtHrs(ms: number): string {
  return `${(ms / 3_600_000).toFixed(2)} h`;
}

export function buildFieldPlanText(s: FieldPlanSnapshot): string {
  const lines = [
    "Moon Transit — field (cheat sheet)",
    "==================================",
    "",
    "TIME",
    `  Anchor + slider (sim.) : ${fmtTime(s.referenceEpochMs)}`,
    `  Time offset (slider)  : ${fmtHrs(s.timeOffsetMs)}`,
    `  Manual skew (ADSB)    : ${(s.latencySkewMs / 1000).toFixed(1)} s (track extrapolation)`,
    "",
    "OBSERVER",
    `  φ, λ, ground alt : ${s.obsLat.toFixed(5)}°, ${s.obsLng.toFixed(5)}°, ${s.obsH.toFixed(0)} m`,
    "",
    "MOON (simulated instant)",
    `  Az, alt, 2R  : ${s.moonAz.toFixed(2)}°, ${s.moonAlt.toFixed(2)}°, ${(2 * s.moonR).toFixed(3)}°`,
    "",
    "AIRCRAFT",
    `  ID  : ${s.flightId ?? "—"}`,
    `  Call: ${s.flightCallSign ?? "—"}`,
    "",
    "PHOTO (estimate, horizontal azimuth)",
    `  to alignment : ${
      s.photoSummary.toImpactSec != null
        ? `${s.photoSummary.toImpactSec.toFixed(1)} s`
        : "—"
    }`,
    `  |ω| horiz   : ${
      s.photoSummary.omegaDps != null
        ? `${s.photoSummary.omegaDps.toFixed(3)}°/s`
        : "—"
    }`,
    `  transit  : ${
      s.photoSummary.transitMs != null
        ? `${(s.photoSummary.transitMs / 1000).toFixed(2)} s`
        : "—"
    }`,
    "",
    "Generated by MoonTransit, manual printout.",
  ];
  return lines.join("\n");
}

export function downloadTextFile(filename: string, content: string) {
  const a = document.createElement("a");
  a.href = URL.createObjectURL(
    new Blob([content], { type: "text/plain;charset=utf-8" })
  );
  a.download = filename;
  a.click();
  setTimeout(() => {
    URL.revokeObjectURL(a.href);
  }, 2_000);
}

export function downloadPngDataUrl(filename: string, dataUrl: string) {
  const a = document.createElement("a");
  a.href = dataUrl;
  a.download = filename;
  a.click();
}

/**
 * Mala mračna „sličica” plana.
 */
export function createFieldPlanPngDataUrl(
  s: FieldPlanSnapshot,
  dpr: number
): string {
  const w = 420;
  const h = 520;
  const c = document.createElement("canvas");
  c.width = w * dpr;
  c.height = h * dpr;
  const g = c.getContext("2d");
  if (!g) {
    return "";
  }
  g.setTransform(1, 0, 0, 1, 0, 0);
  g.scale(dpr, dpr);
  g.fillStyle = "#0a0a0a";
  g.fillRect(0, 0, w, h);
  g.fillStyle = "#a3e635";
  g.font = "600 16px system-ui, sans-serif";
  g.fillText("Moon Transit — field", 20, 32);
  g.fillStyle = "#a1a1aa";
  g.font = "12px system-ui, sans-serif";
  const rows = buildFieldPlanText(s).split("\n");
  let y = 60;
  for (const line of rows.slice(0, 32)) {
    g.fillText(line, 20, y);
    y += 15;
  }
  return c.toDataURL("image/png");
}
